name: kelasku_app
description: A modern Flutter application for managing class schedules and tasks.
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  provider: ^6.1.2
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  image_picker: ^1.1.2
  universal_platform: ^1.0.0+1
  shared_preferences: ^2.2.2
  permission_handler: ^11.0.1
  cached_network_image: ^3.3.1
   

flutter:
  uses-material-design: true
  assets:
    - assets/images/